version: '3.7'

services:
  web:
    container_name: webpage_web
    build:
      context: ./app
      dockerfile: Dockerfile.local
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: ./env/dev/.env
    depends_on:
      - db
  db:
    container_name: webpage_db
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env/dev/.env
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile.local
    command: celery -A config.celery.app worker -l debug
    env_file: ./env/dev/.env
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
      - rabbitmq
  celery-beat:
    build:
      context: ./app
      dockerfile: Dockerfile.local
    command: celery -A config.celery.app beat -l debug --pidfile=
    volumes:
      - ./app/:/usr/src/app/
    env_file: ./env/dev/.env
    depends_on:
      - db
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    environment:
      - TZ=Europe/Warsaw
  flower:
    image: mher/flower
    command: ["flower", "--broker=amqp://rabbitmq", "--port=8888"]
    depends_on:
      - celery
    ports:
      - 8888:8888
volumes:
  postgres_data:
  pgadmin:
