version: '3.7'

services:
  web:
    container_name: webpage_web
    build:
      context: ./app
      dockerfile: Dockerfile.local
    command: python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local
    stdin_open: true
    tty: true
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: ./env/dev/.env
    depends_on:
      - db
    networks:
      webpage:
        ipv4_address: 10.7.0.5
  db:
    container_name: webpage_db
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env/dev/.env
    networks:
      webpage:
        ipv4_address: 10.7.0.6
volumes:
  postgres_data:
  pgadmin:
networks:
  webpage:
    driver: bridge
    ipam:
     config:
       - subnet: 10.7.0.0/16
