# Generated by Django 3.1.4 on 2021-01-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=1),
        ),
    ]
