# Generated by Django 3.1.4 on 2021-01-17 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_auto_20210117_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='pub_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique_for_date='pub_date'),
        ),
    ]
